routes/web.php
<?php



use Illuminate\Support\Facades\Route;



/*

|--------------------------------------------------------------------------

| Web Routes

|--------------------------------------------------------------------------

|

| Here is where you can register web routes for your application. These

| routes are loaded by the RouteServiceProvider within a group which

| contains the "web" middleware group. Now create something great!

|

*/



Auth::routes();



//Route::get('upass', function(){

//    $user = \App\User::where('id', 1)->first();

//    $user->password = bcrypt('Laliga148#');

//    $user->save();

//    $user = \App\User::where('id', 2)->first();

//    $user->password = bcrypt('Parent123#');

//    $user->save();

//});

Route::get('/linking', function () {
  Artisan::call('storage:link');
});

Route::get('/payment', function()
{
    include public_path().'/payment.php';
});


Route::get('/redirectToUserHome', 'Auth\LoginController@redirectToUserHome');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('/', 'Auth\LoginController@showLoginForm')->name('home');
Route::post('/sign-up/store', 'SignUpController@store')->name('sign.up.store');
Route::get('/terms-condition', 'HomeController@laligaTerms')->name('terms.conditions');


/* About Pages */

Route::get('/about', 'HomeController@about')->name('pages.about');

Route::get('/coaches', 'HomeController@coaches')->name('pages.coaches');

Route::get('/photos', 'HomeController@photos')->name('pages.photos');

Route::get('/videos', 'HomeController@videos')->name('pages.videos');



/* Programs Pages */

Route::get('/methodology', 'HomeController@methodologyProgram')->name('pages.methodology_program');

Route::get('/development-program', 'HomeController@developmentProgram')->name('pages.development_program');

Route::get('/advanced-development-program', 'HomeController@advancedDevelopmentProgram')->name('pages.advanced_development_program');

Route::get('/laliga-hpc-program', 'HomeController@laligaHpcProgram')->name('pages.laliga_hpc_program');

Route::get('/summer-program', 'HomeController@summerProgram')->name('pages.summer_program');



/* Scouting Pages */

Route::get('/laliga-trials', 'HomeController@laligaTrials')->name('pages.laliga_trials');

Route::get('/contract-awards', 'HomeController@contractAwards')->name('pages.contract_awards');

Route::get('/soccer-scholarship', 'HomeController@soccerScholarship')->name('pages.soccer_scholarship');



/* Schedule Pages */

Route::get('/development-schedule', 'HomeController@developmentSchedule')->name('pages.development_schedule');

Route::get('/advanced-schedule', 'HomeController@advancedSchedule')->name('pages.advanced_schedule');

Route::get('/training-locations', 'HomeController@trainingLocations')->name('pages.training_locations');



/* Extra Pages */

Route::get('/fees', 'HomeController@fees')->name('pages.fees');

Route::get('/faq', 'HomeController@faq')->name('pages.faq');

Route::get('/privacy-policy', 'HomeController@policy')->name('pages.privacy_policy');

Route::get('/terms-conditions', 'HomeController@terms')->name('pages.terms_conditions');

Route::get('/register-terms-conditions', 'HomeController@registerTermsConditions')->name('pages.register_terms_condtions');




/* Admin Area */

Route::name('admin.')->prefix('admin/')->middleware(['admin'])->group(function(){



    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::get('dashboard', 'HomeController@adminDashboard')->name('_dashboard');

     Route::group(['prefix' => 'custom-invoices'], function () {

     Route::get('/player/{player}/term/{term}', 'InvoiceController@customInvoice')->name('player.term.custom.invoice');

    Route::post('/player/{player}/term/{term}/store', 'InvoiceController@customInvoiceStore')->name('player.term.custom.invoice.store');

     Route::get('/{team}/edit', 'TeamController@edit')->name('teams.edit');

     Route::put('/{team}/update','TeamController@update')->name('teams.update');

     Route::delete('/{team}', 'TeamController@destroy')->name('teams.destroy');

    });



    Route::group(['prefix' => 'seasons'],function () {

    Route::get('/', 'Admin\SeasonController@index')->name('seasons.index');

    Route::get('/create', 'Admin\SeasonController@create')->name('seasons.create');

    Route::post('/', 'Admin\SeasonController@store')->name('seasons.store');

    Route::get('/{season}/edit', 'Admin\SeasonController@edit')->name('seasons.edit');

    Route::put('/{season}/update', 'Admin\SeasonController@update')->name('seasons.update');

    Route::delete('/{season}', 'Admin\SeasonController@destroy')->name('seasons.destroy');

    // Terms



    Route::get('/{season}/Terms', 'Admin\TermsController@index')->name('season.terms.index');

    Route::get('/{season}/Terms/create', 'Admin\TermsController@create')->name('season.terms.create');

    Route::post('/Terms', 'Admin\TermsController@store')->name('season.terms.store');

    Route::get('/{season}/Terms/{term}/edit', 'Admin\TermsController@edit')->name('season.terms.edit');

    Route::put('/Terms/{term}/update', 'Admin\TermsController@update')->name('season.terms.update');

    Route::delete('/{season}/Term/{term}/delete', 'Admin\TermsController@destroy')->name('season.terms.destroy');
  


        Route::get('/', 'Admin\SeasonController@index')->name('seasons.index');

        Route::get('/create', 'Admin\SeasonController@create')->name('seasons.create');

        Route::post('/', 'Admin\SeasonController@store')->name('seasons.store');

        Route::get('/{season}/edit', 'Admin\SeasonController@edit')->name('seasons.edit');

        Route::put('/{season}/update', 'Admin\SeasonController@update')->name('seasons.update');

        Route::delete('/{season}', 'Admin\SeasonController@destroy')->name('seasons.destroy');

        // Terms



        Route::get('/{season}/Terms', 'Admin\TermsController@index')->name('season.terms.index');

        Route::get('/{season}/Terms/create', 'Admin\TermsController@create')->name('season.terms.create');

        Route::post('/terms', 'Admin\TermsController@store')->name('season.terms.store');

        Route::get('/{season}/Terms/{term}/edit', 'Admin\TermsController@edit')->name('season.terms.edit');

        Route::put('/terms/{term}/update', 'Admin\TermsController@update')->name('season.terms.update');

        Route::delete('/{season}/Terms/{term}', 'Admin\TermsController@destroy')->name('season.terms.destroy');
        
        Route::get('/{season}/Terms/{term}/break', 'Admin\TermsController@createTermbreak')->name('season.terms.break');
       
        Route::post('/{season}/Terms/{term}/break/store', 'Admin\TermsController@storeTermbreak')->name('season.term.break.store');

        Route::delete('/{season}/Terms/{term}/break/{break}', 'Admin\TermsController@destroyTermBreak')->name('season.terms.break.destroy');
       // Training Sessions
       

        Route::get('/training-session', 'Admin\TrainingSessionController@index')->name('training.sessions.index');

        Route::get('/term/{term}/training-session/create', 'Admin\TrainingSessionController@create')->name('training.sessions.create');

        Route::post('/term/{term}/training-session/store', 'Admin\TrainingSessionController@store')->name('season.term.training.sessions.store');

        

        Route::get('term/{term}/training-sessions/edit', 'Admin\TrainingSessionController@edit')->name('training.sessions.edit');

         

         Route::get('/training-session/{session}/edit/details', 'Admin\TrainingSessionController@editDetails')->name('training.sessions.edit.details');



        Route::put('training-session/{session}/update', 'Admin\TrainingSessionController@update')->name('training.sessions.update');

        Route::delete('term/{term}/training-sessions/edit/{session}','Admin\TrainingSessionController@destroy')->name('season.term.training.sessions.destroy');

         Route::get('/training-session/search', 'Admin\TrainingSessionController@search')->name('training.sessions.serach');
          

    });



    Route::group(['prefix' => 'emirates'], function () {

        Route::get('/', 'Admin\EmirateController@index')->name('emirates.index');

        Route::get('/create', 'Admin\EmirateController@create')->name('emirates.create');

        Route::post('/', 'Admin\EmirateController@store')->name('emirates.store');

        Route::get('/{emirate}/edit', 'Admin\EmirateController@edit')->name('emirates.edit');

        Route::put('/{emirate}/update', 'Admin\EmirateController@update')->name('emirates.update');

        Route::delete('/{emirate}', 'Admin\EmirateController@destroy')->name('emirates.destroy');

    });

       Route::group(['prefix' => 'user-accounts'], function () {

        Route::get('/', 'UserController@accounts')->name('accounts.index');

        Route::get('/create', 'UserController@createAccount')->name('accounts.create');

        Route::post('/', 'UserController@storeAccount')->name('accounts.store');

        Route::get('/{user}/edit', 'UserController@editAccount')->name('accounts.edit');

        Route::put('/{user}/update', 'UserController@updateAccount')->name('accounts.update');

        Route::delete('/{user}', 'UserController@destroy')->name('accounts.destroy');

    });



    Route::group(['prefix' => 'age-categories'], function () {

        Route::get('/', 'Admin\AgeCategoryController@index')->name('age.categories.index');

        Route::get('/create', 'Admin\AgeCategoryController@create')->name('age.categories.create');

        Route::post('/', 'Admin\AgeCategoryController@store')->name('age.categories.store');

        Route::get('/{category}/edit', 'Admin\AgeCategoryController@edit')->name('age.categories.edit');

        Route::put('/{category}/update', 'Admin\AgeCategoryController@update')->name('age.categories.update');

        Route::delete('/{category}', 'Admin\AgeCategoryController@destroy')->name('age.categories.destroy');

    });

app/Term.php
<?php



namespace App;



use Illuminate\Database\Eloquent\Model;

use Illuminate\Database\Eloquent\SoftDeletes;

use Carbon\Carbon;



class Term extends Model

{

  use SoftDeletes;

  protected $dates = ['deleted_at','start_date', 'end_date'];

  public function locations()

    {

        return $this->belongsToMany('App\Location')->withTimestamps();

    }



  public function getStartDateFormattedAttribute()

    {

        return Carbon::parse($this->start_date)->format('d/m/Y');

    }



    public function getEndDateFormattedAttribute()

    {

        return Carbon::parse($this->end_date)->format('d/m/Y');

    } 



    public function trainingSession()

    {

        return $this->hasMany('App\TrainingSession');

    } 



    public function players()

    {

        return $this->belongsToMany('App\Player')->withTimestamps()->withPivot(['emirate_id','is_kit_amount_paid','kit_size','is_active','kit_status','is_sponsored','match_kit','payment_status','id','term_id','team_id','serial_no','fee_amount']);

    }



    public function getEmirate($id)

    {

        $emirate=Emirate::find($id);

        return $emirate->name;

    }



    public function season()

    {

       return $this->belongsTo('App\Season');

    

    }





}

resources/views/admin/terms/_form.blade.php
<div class="box-body">

    <div class="control-group{{ $errors->has('name') ? ' has-error' : '' }}">
        {!! Form::label('name', 'Name', ['class'=>'form-label']) !!}

        {!! Form::text('name', null, ['class'=>'form-field','required' => 'required','maxlength'=>'100','placeholder'=>'Name']) !!}

        @if ($errors->has('name'))
        <span class="error-msg">
            <strong>{{ $errors->first('name') }}</strong>
        </span>
        @endif
    </div>

    <div class="control-group{{ $errors->has('start_date') ? ' has-error' : '' }}">

        {!! Form::label('start_date', 'Start Date', ['class'=>'form-label']) !!}

        <div class='input-group'>
            {!! Form::text('start_date',null,['class'=>'form-field','id'=>'start_date','autocomplete'=>'off']) !!}
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>

        @if ($errors->has('start_date'))
        <span class="error-msg">
            <strong>{{ $errors->first('start_date') }}</strong>
        </span>
        @endif

    </div>

    <div class="control-group{{ $errors->has('end_date') ? ' has-error' : '' }}">

        {!! Form::label('end_date', 'End Date', ['class'=>'form-label']) !!}

        <div class='input-group'>
            {!! Form::text('end_date',null,['class'=>'form-field','id'=>'end_date','data-date-format'=>'yyyy-mm-dd','autocomplete'=>'off']) !!}
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>

        @if ($errors->has('end_date'))
        <span class="error-msg">
            <strong>{{ $errors->first('end_date') }}</strong>
        </span>
        @endif
    </div>

     <div class="control-group{{ $errors->has('type_id') ? ' has-error' : '' }}">

        {!! Form::label('type', 'Select Type', ['class' => 'form-label']) !!}

        {!! Form::select('type_id',$types,null, ['class'=>'form-field','required' => 'required']) !!}

        @if ($errors->has('type_id'))
        <span class="invalid-feedback" role="alert">
            <strong>{{ $errors->first('type_id') }}</strong>
        </span>
        @endif
    </div>

    <div class="control-group{{ $errors->has('level') ? ' has-error' : '' }}">
        
        {!! Form::label('level', 'Select Level', ['class' => 'form-label']) !!}
        

        {!! Form::select('level',$levels,null, ['class'=>'form-field','required' => 'required']) !!}
         
        @if ($errors->has('level'))
        <span class="invalid-feedback" role="alert">
            <strong>{{ $errors->first('level') }}</strong>
        </span>
        @endif
    </div>

    <div class="control-group{{ $errors->has('kit_amount') ? ' has-error' : '' }}">

        {!! Form::label('kit_amount', 'Kit Amount', ['class'=>'form-label']) !!}

        {!! Form::text('kit_amount', null, ['class'=>'form-field','placeholder'=>'Kit Amount']) !!}

        @if ($errors->has('kit_amount'))
        <span class="error-msg">
            <strong>{{ $errors->first('kit_amount') }}</strong>
        </span>
        @endif
    </div>

    <div class="control-group{{ $errors->has('total_sessions') ? ' has-error' : '' }}">

        {!! Form::label('total_sessions', 'Total Sessions', ['class'=>'form-label']) !!}

        {!! Form::text('total_sessions', null, ['class'=>'form-field','placeholder'=>'Total Sessions']) !!}

        @if ($errors->has('total_sessions'))
        <span class="error-msg">
            <strong>{{ $errors->first('total_sessions') }}</strong>
        </span>
        @endif
    </div>

      <div class="control-group{{ $errors->has('weeks') ? ' has-error' : '' }}">

        {!! Form::label('weeks', 'Weeks', ['class'=>'form-label']) !!}

        {!! Form::text('weeks', null, ['class'=>'form-field','placeholder'=>'Weeks']) !!}

        @if ($errors->has('weeks'))
        <span class="error-msg">
            <strong>{{ $errors->first('weeks') }}</strong>
        </span>
        @endif
    </div>

    <div class="control-group{{ $errors->has('is_show_to_admin') ? ' has-error' : '' }}">

        <div class="checkbox">
            {!! Form::checkbox('is_show_to_admin', 1, isset($term) ? $term->is_show_to_admin : true) !!}

            <span class="label"></span>
            <span class="text">
                {!! Form::label('is_show_to_admin', 'Show to Admin', ['class' => 'form-label']) !!}
            </span>
        </div>

        @if ($errors->has('is_show_to_admin'))
        <span class="error-msg">
            <strong>{{ $errors->first('is_show_to_admin') }}</strong>
        </span>
        @endif
    </div>

    <div class="control-group{{ $errors->has('is_active') ? ' has-error' : '' }}">

        <div class="checkbox">
            {!! Form::checkbox('is_active', 1, isset($term) ? $term->is_active : true) !!}

            <span class="label"></span>
            <span class="text">
                {!! Form::label('is_active', 'Activate', ['class' => 'form-label']) !!}
            </span>
        </div>

        @if ($errors->has('is_active'))
        <span class="error-msg">
            <strong>{{ $errors->first('is_active') }}</strong>
        </span>
        @endif
    </div>

    <div class="control-group{{ $errors->has('yearly') ? ' has-error' : '' }}">

        <div class="checkbox">
            {!! Form::checkbox('yearly', 1, isset($term) ? $term->yearly : true) !!}

            <span class="label"></span>
            <span class="text">
                {!! Form::label('yearly', 'Yearly', ['class' => 'form-label']) !!}
            </span>
        </div>

        @if ($errors->has('yearly'))
        <span class="error-msg">
            <strong>{{ $errors->first('yearly') }}</strong>
        </span>
        @endif
    </div>

    {!! Form::hidden('season_id',$season, ['class'=>'form-field']) !!}
    <div class="control-group mb-0">

        <button type="submit" class="btn --btn-small bg-secondary fc-white" id="submit">{{ $submitBtnText }}</button>
        <a href="{{ url()->previous() }}" class="btn --btn-small bg-danger fc-white">Cancel</a>
    </div>

</div>

<script>
    var dateToday = new Date();
    
    $( "#start_date" ).datepicker({
        //minDate: dateToday,
    });

    $( "#end_date" ).datepicker({
        //minDate: dateToday,
    });
</script>

resources/views/admin/terms/break.blade.php
@extends('layouts.admin')
@section('content')
<h3 class="pagetitle">Term Break-{{$term->name}}</h3>
<section class="box">
	@include('includes.message')
	<div class="box-body">
		{!! Form::open(['route' => ['admin.season.term.break.store',[$season,$term->id]], 'files' => 'true', 'method' => 'POST', 'enctype'=>"multipart/form-data",'class'=>"default-form"]) !!}
		
		
		<div class="row">
			<div class="col-sm-6">
				<div class="control-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
					{!! Form::label('start_date', 'Start Date', ['class'=>'form-label']) !!}
					<div class='input-group'>
						{!! Form::text('start_date',null,['class'=>'form-field','autocomplete'=>'off']) !!}
						<span class="input-group-addon">
							<span class="glyphicon glyphicon-calendar"></span>
						</span>
					</div>
					@if ($errors->has('start_date'))
					<span class="error-msg">
						<strong>{{ $errors->first('start_date') }}</strong>
					</span>
					@endif
				</div>
			</div>
			
			<div class="col-sm-6">
				<div class="control-group{{ $errors->has('end_date') ? ' has-error' : '' }}">
					{!! Form::label('end_date', 'End Date', ['class'=>'form-label']) !!}
					<div class='input-group'>
						{!! Form::text('end_date',null,['class'=>'form-field','autocomplete'=>'off']) !!}
						<span class="input-group-addon">
							<span class="glyphicon glyphicon-calendar"></span>
						</span>
					</div>
					@if ($errors->has('end_date'))
					<span class="error-msg">
						<strong>{{ $errors->first('end_date') }}</strong>
					</span>
					@endif
				</div>
			</div>
		</div>
	    <div class="form-group">
				<center>
				<input type="submit" value="Update" class="btn --btn-small bg-secondary fc-white">
				<a href="{{ url()->previous() }}" class="btn --btn-small bg-danger fc-white">Cancel</a></center>
				
			</div>
		</div>
		<table class="table --bordered --hover">
      <tr>
        <th><center>S NO</center></th>
        <th><center>Term Name</center></th>
        <th><center>Start Date</center></th>
        <th><center>End Date</center></th>
        <th><center>Action</center></th>
      </tr>
      <tr>
        @foreach ($term_break as $key=>$break)
        <tr>
          
          <td>
            <center>{{$term_break->firstItem() + $key }}</center>
          </td>
          <td>
            <center>{{ $break->term->name }}</center>
          </td>
          <td>
            {{$break->start_date}}
            
          </td>
          <td><center>
             {{$break->end_date}}
            </center>
          </td>
          
          <td>
            <center>
            <button type="button" class="deleteItem btn --btn-small bg-danger fc-white" data-delete-id="{{ $break->id }}" id="deleteItem">Delete</button>
            </center>
          </td>
        </tr>
        @endforeach
      </table>
		{!! Form::close() !!}
	</div>
</section>
<script>
var dateToday = new Date();
$( ".form-field" ).datepicker({
       
    });
</script>
{!! Form::open(['method' => 'delete', 'id' => 'deleteForm']) !!}
    {!! Form::close() !!}
    <script>
    var deleteResourceUrl = '{{ url()->current() }}';
    $(document).ready(function () {
    $('.deleteItem').click(function (e) {
    e.preventDefault();
    var deleteId = parseInt($(this).data('deleteId'));
    $('#deleteForm').attr('action', deleteResourceUrl + '/' + deleteId);
    if (confirm('Are you sure?')) {
    $('#deleteForm').submit();
    }
    });
    });
    </script>
@endsection

resources/views/admin/terms/create.blade.php
@extends('layouts.admin')
@section('content')
<h3 class="pagetitle">Add Term</h3>
<section class="box">
	{!! Form::open(['route' => 'admin.season.terms.store', 'files' => 'true', 'method' => 'POST', 'enctype'=>"multipart/form-data",'class'=>"default-form"]) !!}
	@include('admin.terms._form',['submitBtnText' => 'Add Terms'])
	{!! Form::close() !!}
</div>
</section>
@endsection

resources/views/admin/terms/edit.blade.php
@extends('layouts.admin')
@section('content')
<h3 class="pagetitle">Edit Term</h3>
<section class="box">
	<section class="box">
		<div class="box-header">
			<div class="row align-items-center">
				<div class="col-8">
				</div>
				
				<div class="col-4">
					<a href="{{route('admin.dashboard')}}" class="btn --btn-small bg-secondary fc-white mb-0 float-right">Back</a>
				</div>
			</div>
		</div>
		<div class="box-body">
			{!! Form::model($term, ['route' => ['admin.season.terms.update', $term->id], 'files' => 'true', 'method' => 'PUT', 'enctype'=>"multipart/form-data",'class'=>"default-form"]) !!}
			@include('admin.terms._form',['submitBtnText' => 'Update'])
			{!! Form::close() !!}
		</div>
	</section>
	@endsection

resources/views/admin/terms/index.blade.php
@extends('layouts.admin')
@section('content')
<h3 class="pagetitle">Terms</h3>
@include('includes.message')
<section class="box">
    <div class="box-header">
        <div class="row align-items-center">
            <div class="col-8">
                <a href="{{route('admin.season.terms.create',[$season])}}" class="btn --btn-small --btn-primary mb-0">Add Term</a>
            </div>
            
            <div class="col-4">
                <a href="{{route('admin.dashboard')}}" class="btn --btn-small bg-secondary fc-white mb-0 float-right">Back</a>
            </div>
        </div>
    </div>
    <div class="box-body">
        <table class="table --bordered --hover">
            <tr>
                <th><center>S NO</center></th>
                <th>Name</th>
                <th><center>Type</center></th>
                <th><center>Start Date</center></th>
                <th><center>End Date</center></th>
                <th><center>Is Active</center></th>
                <th><center>Action</center></th>
            </tr>
            
            @foreach ($terms as $key=>$term)
            <tr>
                <td>
                    <center>{{ $terms->firstItem() + $key }}</center>
                </td>
                <td>
                    {{ $term->name }}
                </td>
                <td>
                    <center>
                    @foreach($types as $key => $type)
                    @if($term->type_id==$key)
                    <center>{{ $type }}</center>
                    @endif
                    @endforeach
                    </center>
                </td>
                <td>
                    <center>@if(!empty($term->start_date)){{ date('Y-m-d',strtotime($term->start_date))}}@endif</center>
                </td>
                <td>
                    <center>@if(!empty($term->end_date)){{ date('Y-m-d',strtotime($term->end_date))}}@endif</center>
                </td>
                <td>
                    <center>
                    @if($term->is_active)
                    <p>Active</p>
                    @else
                    <p>InActive</p>
                    @endif
                    </center>
                </td>
                <td>
                  <center>
                    <a href="{{ route('admin.season.terms.edit',[$season,$term->id]) }}" class="btn --btn-small bg-secondary fc-white btn-sm" style="width: 150px;">Edit</a><br>
                    <a href="{{ route('admin.season.terms.break',[$season,$term->id]) }}" class="btn --btn-small bg-primary fc-white btn-sm" style="width: 150px;">Break</a><br>
                    <button type="button" class="deleteItem btn --btn-small bg-danger fc-white btn-sm" data-delete-id="{{ $term->id }}" id="deleteItem" style="width: 150px;">Delete </button>
                   </center>
                </td>
            </tr>
            @endforeach
        </table>
        
        <div class="">
            {{$terms->links()}}
        </div>
    </div>
</section>
{!! Form::open(['method' => 'delete', 'id' => 'deleteForm']) !!}
{!! Form::close() !!}
<script>
var deleteResourceUrl = '{{ url()->current() }}';
$(document).ready(function () {
$('.deleteItem').click(function (e) {
e.preventDefault();
var deleteId = parseInt($(this).data('deleteId'));
$('#deleteForm').attr('action', deleteResourceUrl + '/' + deleteId);
if (confirm('Are you sure?')) {
$('#deleteForm').submit();
}
});
});
</script>
@endsection